---
ERC:
  stage: test
  image: ghcr.io/kicad/kicad:9.0
  script:
    - kicad-cli sch erc voltage-divider/voltage-divider.kicad_sch
    - cat voltage-divider-erc.rpt

DRC:
  stage: test
  image: ghcr.io/kicad/kicad:9.0
  script:
    - kicad-cli pcb drc voltage-divider/voltage-divider.kicad_pcb
    - cat voltage-divider-drc.rpt
